language: julia
julia:
    - 0.6
after_success:
    - julia -e 'cd(Pkg.dir("UEM")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
    - julia -e 'Pkg.add("Documenter")'
    - julia -e 'cd(Pkg.dir("UEM")); include(joinpath("docs", "make.jl"))'
